baseURL = 'https://madhavkhoslaa.github.io/'
languageCode = 'en'
title = 'Madhav Khosla'
theme = "risotto"
author = "Madhav Khosla"
copyright = "© Madhav Khosla"

enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true
pygmentsUseClasses = true

ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 5

[params]
  noindex = false

[params.theme]
  palette = "base16-dark"

[params.about]
  title = "Madhav Khosla"
  description = "Backend Engineer | Crypto Enthusiast"

[[params.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://bit.ly/3Qyr87Y"

[[params.socialLinks]]
  icon = "fa-brands fa-twitter"
  title = "Twitter"
  url = "https://bit.ly/3Qtgn6y"

[[params.socialLinks]]
  icon = "fa-brands fa-linkedin"
  title = "LinkedIn"
  url = "https://bit.ly/4ezgvhX"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 5
  [[menu.main]]
    identifier = "draft"
    name = "Draft"
    url = "/draft/"
    weight = 6

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true
